<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UniversalSompoCarAddonConfigurationUpdated08sept extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('universal_sompo_car_addon_configuratio
        n')->truncate();
        DB::table('universal_sompo_car_addon_configuration')->insert(
            array(
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "0-1",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "1-2",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "2-3",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "3-4",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "4-5",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "5-6",
                    "zero_dep" => "True",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "6-7",
                    "zero_dep" => "True",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "7-10",
                    "zero_dep" => "False",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "False",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "honda",
                    "age_range" => "10-15",
                    "zero_dep" => "False",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "False",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "0-1",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "1-2",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "2-3",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "3-4",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "4-5",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "5-6",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "6-7",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "7-10",
                    "zero_dep" => "True",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "maruti",
                    "age_range" => "10-15",
                    "zero_dep" => "False",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "False",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "0-1",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "True",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "1-2",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "True",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "2-3",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "True",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "3-4",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "True",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "4-5",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "True",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "5-6",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "True",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "6-7",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "True",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "7-10",
                    "zero_dep" => "False",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "False",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "tata",
                    "age_range" => "10-15",
                    "zero_dep" => "False",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "False",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "0-1",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "True",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "1-2",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "True",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "2-3",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "True",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "3-4",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "True",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "4-5",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "True",
                    "road_side_assistance" => "True",
                    "key_replacement" => "True",
                    "consumable" => "True",
                    "tyre_secure" => "True",
                    "loss_of_belongings" => "True",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "5-6",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "6-7",
                    "zero_dep" => "True",
                    "engine_protector" => "True",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "True",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "7-10",
                    "zero_dep" => "False",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "False",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => "make_other_than_oem",
                    "age_range" => "10-15",
                    "zero_dep" => "False",
                    "engine_protector" => "False",
                    "return_to_invoice" => "False",
                    "road_side_assistance" => "True",
                    "key_replacement" => "False",
                    "consumable" => "False",
                    "tyre_secure" => "False",
                    "loss_of_belongings" => "False",
                    "ncb_protector" => "False",
                ),
                array(
                    "vehicle_make" => NULL,
                    "age_range" => NULL,
                    "zero_dep" => NULL,
                    "engine_protector" => NULL,
                    "return_to_invoice" => NULL,
                    "road_side_assistance" => NULL,
                    "key_replacement" => NULL,
                    "consumable" => NULL,
                    "tyre_secure" => NULL,
                    "loss_of_belongings" => NULL,
                    "ncb_protector" => "False",
                ),
            )
        );
    }
}
