<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class DeleteUnuserTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::dropIfExists('sale_mast');
        Schema::dropIfExists('claim_documents');
        Schema::dropIfExists('claim_remarks');
        Schema::dropIfExists('category');
        Schema::dropIfExists('cancellation_request_mapping_docs');
        Schema::dropIfExists('broker_ic_map');
        Schema::dropIfExists('broker_ic_addon_map');
        Schema::dropIfExists('surveyor_category');
        Schema::dropIfExists('segment_version_map');
        Schema::dropIfExists('renewal_notice_master');
        Schema::dropIfExists('refund');
        Schema::dropIfExists('claims');
        Schema::dropIfExists('policywise_segment');
        Schema::dropIfExists('pos_user');
        Schema::dropIfExists('corporate_branch');
        Schema::dropIfExists('configure_report');
        Schema::dropIfExists('common_transaction_detail');
        Schema::dropIfExists('ic_model_master');
        Schema::dropIfExists('previous_policy_type');
        Schema::dropIfExists('claim_settlement');
        Schema::dropIfExists('product_gst_mapping');
        Schema::dropIfExists('product_rto_zone');
        Schema::dropIfExists('product_type_ic_map');
        Schema::dropIfExists('proposal_details');
        Schema::dropIfExists('proposal_ic_surveyor_map');
        Schema::dropIfExists('proposal_payment_map');
        Schema::dropIfExists('surveyor_claim_mapping');
        Schema::dropIfExists('refund_remarks');
        Schema::dropIfExists('product_mapping');
        Schema::dropIfExists('surveyor_document');
        Schema::dropIfExists('endorsement_remarks');
        Schema::dropIfExists('branch_territory');
        Schema::dropIfExists('user_product_journey_idv');
        Schema::dropIfExists('user_product_mapping');
        Schema::dropIfExists('history');
        Schema::dropIfExists('gcv_fyntune_master');
        Schema::dropIfExists('gcv_make');
        Schema::dropIfExists('users_addons');
        Schema::dropIfExists('veh_type_rto_map');
        Schema::dropIfExists('vehicle_ccwise_segment');
        Schema::dropIfExists('vehicle_discount');
        Schema::dropIfExists('gcv_model');
        Schema::dropIfExists('gcv_motor_tarif');
        Schema::dropIfExists('vehicle_type');
        Schema::dropIfExists('vehicle_type_registration');
        Schema::dropIfExists('vehicle_uses');
        Schema::dropIfExists('gcv_tppd');
        Schema::dropIfExists('ic_category_map');
        Schema::dropIfExists('user_payment_mode_map');
        Schema::dropIfExists('user_menu_map');
        Schema::dropIfExists('user_login_token');
        Schema::dropIfExists('bike_model_version');
        Schema::dropIfExists('bike_model');
        Schema::dropIfExists('bike_manufacturer');
        Schema::dropIfExists('authority');
        Schema::dropIfExists('admin_users');
        Schema::dropIfExists('addon_bundle_mapping');
        // Schema::dropIfExists('telescope_monitoring');
        Schema::dropIfExists('surveyor_report');
        Schema::dropIfExists('ic_details_gst');
        Schema::dropIfExists('test_premium_calculate_jivan');
        Schema::dropIfExists('testcheck');
        Schema::dropIfExists('addon_bundle');
        Schema::dropIfExists('tmp_export');
        Schema::dropIfExists('transaction_table_proposal');
        Schema::dropIfExists('user_category_map');
        Schema::dropIfExists('addon_apply_on');
        Schema::dropIfExists('template_master_old');
        Schema::dropIfExists('policy_wise_sub_segment');
        Schema::dropIfExists('corporate_client_product_map');
        Schema::dropIfExists('policy_summary_details');
        Schema::dropIfExists('discount_schema');
        Schema::dropIfExists('digit_gcv_master');
        Schema::dropIfExists('master_office');
        Schema::dropIfExists('master_payment_mode');
        Schema::dropIfExists('master_permission');
        Schema::dropIfExists('decline_rto');
        Schema::dropIfExists('exc_data_validation');
        Schema::dropIfExists('decline_regstration_no');
        Schema::dropIfExists('master_regional_office');
        Schema::dropIfExists('decline_mmv');
        Schema::dropIfExists('master_rto_cluster');
        Schema::dropIfExists('master_salutation');
        Schema::dropIfExists('master_segment');
        Schema::dropIfExists('master_segment_group');
        // Schema::dropIfExists('failed_jobs');
        Schema::dropIfExists('master_ic_rto_test');
        Schema::dropIfExists('master_ic_rto_demo');
        Schema::dropIfExists('master_ic_rto');
        Schema::dropIfExists('endorsement_details');
        Schema::dropIfExists('ll_cover');
        Schema::dropIfExists('lso_mapping');
        Schema::dropIfExists('email_quote_log');
        Schema::dropIfExists('master_area');
        Schema::dropIfExists('master_branch_office');
        Schema::dropIfExists('master_brokers');
        Schema::dropIfExists('master_bundle_addon');
        Schema::dropIfExists('master_car_insurance');
        Schema::dropIfExists('master_city');
        Schema::dropIfExists('endorsement_status_master');
        Schema::dropIfExists('master_corporate_client');
        Schema::dropIfExists('master_district');
        Schema::dropIfExists('master_garage');
        Schema::dropIfExists('endorsement_type');
        Schema::dropIfExists('liberty_videocon_bike_model_master');
        Schema::dropIfExists('policy_wise_sub_rto_cluster');
        Schema::dropIfExists('master_state_dist_city_map_ic');
        Schema::dropIfExists('cv_quote_agent_mapping');
        Schema::dropIfExists('number_generator_table');
        Schema::dropIfExists('od_discount_master');
        Schema::dropIfExists('cover_details');
        Schema::dropIfExists('corporate_vehicles_policy_detail');
        Schema::dropIfExists('password_resets');
        Schema::dropIfExists('fuel_type');
        Schema::dropIfExists('credit_trigger_table');
        Schema::dropIfExists('payment_mode');
        Schema::dropIfExists('payment_status');
        Schema::dropIfExists('payout_heads_master');
        Schema::dropIfExists('payout_master');
        Schema::dropIfExists('ic_surveyor_report');
        Schema::dropIfExists('liberty_videocon_pincode_state_city_master_old');
        Schema::dropIfExists('corporate_client_ic_map');
        Schema::dropIfExists('corporate_vehicles_details');
        Schema::dropIfExists('motor_tppd');
        Schema::dropIfExists('ft_ic_rto_map');
        Schema::dropIfExists('gst_cess_calculation');
        Schema::dropIfExists('cv_proposal_agent_mapping');
        Schema::dropIfExists('mis_report');
        Schema::dropIfExists('mis_user_custom_report');
        Schema::dropIfExists('mis_user_details');
        Schema::dropIfExists('ledger_table');
        Schema::dropIfExists('module');
        Schema::dropIfExists('module_users_mapping');
        Schema::dropIfExists('ledger_account');
        Schema::dropIfExists('motor_features');
        Schema::dropIfExists('icici_rto_master_new');
        Schema::dropIfExists('motor_lpgcng');
        Schema::dropIfExists('cubic_capacity');
        Schema::dropIfExists('cron_time_log');
        Schema::dropIfExists('finance_type');
        Schema::dropIfExists('master_zone_office');
        Schema::dropIfExists('motor_risk_details');
        Schema::dropIfExists('all_web_service_request_response');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
