<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 4.0.5(168)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateGodigitPincodeStateCityMasterTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('godigit_pincode_state_city_master', function (Blueprint $table) {
            $table->integer('pincode');
            $table->text('state');
            $table->text('statecode');
            $table->text('statecodetext');
            $table->text('district');
            $table->text('city');
            $table->text('country');
        });
    }
   
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('godigit_pincode_state_city_master');
    }
}
