version: '3.8'

services:
  backend:
    build:
      context: ./motor_2.0_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./motor_2.0_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: motor
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
