<?php

return [
    'quote' => [
        "Coverage Calculation",
        "Premium Calculation",
        "premiumCalculation",
        "tokenGeneration",
        "Premium Calculation - prime",
        "Premium Recalculation",
        "Premium Re Calculation",
        "Premium Calculation - Full Quote",
        "Premium Re Calculation - prime",
        "addonsCoverService",
        "Change IDV calcualtion",
        "Change IDV Calculation - Quote",
        "Customer Creation",
        "Fetch Policy Details",
        "Get Token",
        "IDV Calculation",
        "IDV calculations",
        "IDV Service",
        "Premium Calculation - ",
        "Premium Calculation - basic",
        "Premium Calculation - DRIVE_ASSURE_BASIC",
        "Premium Calculation - DRIVE_ASSURE_PACK",
        "Premium Calculation - DRIVE_ASSURE_PACK_PLUS",
        "Premium Calculation - DRIVE_ASSURE_SILVER",
        "Premium Calculation - DRIVE_ASSURE_SPOT",
        "Premium Calculation - IDV change",
        "Premium Calculation - IMT-23",
        "Premium Calculation - od_only",
        "Premium Calculation - Quote",
        "Premium Calculation - Quote -IDV change",
        "Premium Calculation - TELEMATICS_CLASSIC",
        "Premium Calculation - TELEMATICS_PREMIUM",
        "Premium Calculation - TELEMATICS_PRESTIGE",
        "Premium Calculation - TP only",
        "Premium Calculation - tp_only",
        "Premium Calculation - Zero Dept.",
        "Premium First Call - GDD",
        "Premium First Call - GDD (IDV)",
        "Premium Re Calculation - Basic",
        "Premium Re Calculation - DRIVE_ASSURE_PACK",
        "Premium Re Calculation - DRIVE_ASSURE_PACK_PLUS",
        "Premium Re Calculation - TELEMATICS_CLASSIC",
        "Premium Re Calculation - TELEMATICS_PREMIUM",
        "Premium Re Calculation - TELEMATICS_PRESTIGE",
        "Premium Re-calculation",
        "Premium ReCalculation - basic",
        "Premium ReCalculation - DRIVE_ASSURE_BASIC",
        "Premium ReCalculation - DRIVE_ASSURE_PACK_PLUS",
        "Premium ReCalculation - DRIVE_ASSURE_SILVER",
        "Premium ReCalculation - DRIVE_ASSURE_SPOT",
        "Premium Recalculation - GDD",
        "Premium Recalculation - IMT-23",
        "Premium ReCalculation - od_only",
        "premiumRecalculation",
        "Proposal Submission",
        "Quote",
        "Quote Calculation - Quote",
        "Quote Generation",
        "Quote Generation - IDV change",
        "Quote Generation - IDV changed",
        "Quote Premium Calculation",
        "Token Generation",
        "Token genration",
        "tokenGenerationAddons",
        "TP Premium Calculation",
        "TP Quote",
        "Trace Id Generation",
        "idvService",
        "Premium Calculation - od only",
        "IdvGeneration",
        "Premium ReCalculation - Prime",
        "Premium Calculation - Zero Dept",
        "Premium Calculation -",
        "Premium ReCalculation - od only",
        "TP - Premium Calculation",
    ],
    'quoteAllMethods' => [
        "tokenGeneration" => "Token Generation",
        "Get Token" => "Token Generation",
        "Token Generation" => "Token Generation",
        "Token genration" => "Token Generation",
        "tokenGenerationAddons" => "Token Generation",
        "Coverage Calculation" => "Premium Calculation",
        "IDV Calculation" => "IDV Service",
        "IDV calculations" => "IDV Service",
        "IDV Service" => "IDV Service",
        "idvService" => "IDV Service",
        "IdvGeneration" => "IDV Service",
        "Premium Calculation" => "Premium Calculation",
        "premiumCalculation" => "Premium Calculation",
        "Premium Calculation - IDV" => "Premium Calculation",
        "Premium Calculation - Full Quote" => "Premium Calculation",
        "Premium Calculation - " => "Premium Calculation",
        "Premium Calculation - basic" => "Premium Calculation",
        "Premium Calculation - IMT-23" => "Premium Calculation",
        "Premium Calculation - od_only" => "Premium Calculation",
        "Premium Calculation - Quote" => "Premium Calculation",
        "Premium Calculation - TP only" => "Premium Calculation",
        "Premium Calculation - tp_only" => "Premium Calculation",
        "Premium Calculation - Zero Dept." => "Premium Calculation",
        "Premium First Call - GDD" => "Premium Calculation",
        "Premium First Call - GDD (IDV)" => "Premium Calculation",
        "Quote" => "Premium Calculation",
        "Quote Calculation - Quote" => "Premium Calculation",
        "Quote Generation" => "Premium Calculation",
        "Quote Premium Calculation" => "Premium Calculation",
        "TP Premium Calculation" => "Premium Calculation",
        "TP Quote" => "Premium Calculation",
        "Premium Calculation - od only" => "Premium Calculation",
        "Premium Calculation - Zero Dept" => "Premium Calculation",
        "Premium Calculation -" => "Premium Calculation",
        "TP - Premium Calculation" => "Premium Calculation",
        "Premium Re Calculation - prime" => "Premium Re-Calculation",
        "Change IDV calcualtion" => "Premium Re-Calculation",
        "Change IDV Calculation - Quote" => "Premium Re-Calculation",
        "Premium Re Calculation" => "Premium Re-Calculation",
        "Premium Recalculation" => "Premium Re-Calculation",
        "Premium Calculation - IDV change" => "Premium Re-Calculation",
        "Premium Calculation - Quote -IDV change" => "Premium Re-Calculation",
        "premiumRecalculation" => "Premium Re-Calculation",
        "Premium Recalculation - GDD" => "Premium Re-Calculation",
        "Premium Recalculation - IMT-23" => "Premium Re-Calculation",
        "Premium ReCalculation - od_only" => "Premium Re-Calculation",
        "Quote Generation - IDV change" => "Premium Re-Calculation",
        "Quote Generation - IDV changed" => "Premium Re-Calculation",
        "Premium ReCalculation - Prime" => "Premium Re-Calculation",
        "Premium ReCalculation - od only" => "Premium Re-Calculation",
        "Premium Re Calculation IDV changed" => "Premium Re-Calculation",
    ],
    'proposal' => [
        "tokenGeneration",
        "premiumCalculation",
        "proposalService",
        "Check Breakin Status",
        "Premium Calculation",
        "Proposal Submit",
        "Proposal Generation",
        "PROPOSAL KYC STATUS",
        "Validate Proposal",
        "Submit Proposal - prime",
        "Policy Issuing - prime",
        "Pin Generation",
        "Coverage Calculation",
        "Proposal Creation",
        "Lead Creation",
        "Breakin-Generation",
        "Premium Calculation - Full Quote",
        "Proposal Submition",
        "Proposal Creation - Reliance Finsall",
        "Quote",
        "Customer Creation",
        "Get Token",
        "IDV Service",
        "Token Generation",
        "IDV Calculation",
        "Premium Calculation - Quote",
        "Quote Generation",
        "Premium Recalculation",
        "Quote Calculation - Quote",
        "Premium Calculation - Quote -IDV change",
        "Quote Generation - IDV changed",
        "Premium Re Calculation",
        "Premium Calculation - prime",
        "IDVCalculation",
        "Token genration",
        "Quote Generation - IDV change",
        "Trace Id Generation",
        "Payment - proposal",
        "Proposal Service",
        "TP - Premium Calculation",
        "TP Quote",
        "Submit Proposal - TELEMATICS_CLASSIC",
        "Policy Issuing - TELEMATICS_CLASSIC",
        "Policy Issuing - tp_only",
        "Submit Proposal - tp_only",
        "Premium ReCalculation - basic",
        "Premium ReCalculation - DRIVE_ASSURE_BASIC",
        "Premium ReCalculation - DRIVE_ASSURE_SILVER",
        "Premium ReCalculation - DRIVE_ASSURE_SPOT",
        "Change IDV calcualtion",
        "Change IDV Calculation - Quote",
        "Premium Re Calculation - TELEMATICS_CLASSIC",
        "Premium Re Calculation - Prime",
        "Update Premium Calculation",
        "Premium Re-calculation",
        "Premium submition",
        "Proposal Generation - basic",
        "Submit Proposal - Basic",
        "Proposal Submission",
        "Proposal Generation - DRIVE_ASSURE_BASIC",
        "Proposal Submition - Proposal",
        "Proposal Generation - DRIVE_ASSURE_SILVER",
        "Proposal Generation - TP only",
        "Premium ReCalculation - od only",
        "Quick Quote - Proposal",
        "Full Quote - Proposal",
        "Proposal Generation - od only",
        "IIB Verification",
        "Proposal Status",
        "Save Quote And Approve Proposal",
        "Breakin Creation",
        "Break-in Id Generation",
        "Break id generation",
        "Proposal Approval",
        "Proposal",
        "Submit Proposal - DRIVE_ASSURE_PACK_PLUS",
        "Policy Issuing - DRIVE_ASSURE_PACK_PLUS",
        "Submit Proposal",
        "save motor quotation",
        "generate transation",
        "save motor proposal",
        "Policy Issuing - TELEMATICS_PREMIUM",
        "Submit Proposal - TELEMATICS_PREMIUM",
        "Policy Issuing - TELEMATICS_PRESTIGE",
        "Submit Proposal - TELEMATICS_PRESTIGE",
        "Policy Issuing - DRIVE_ASSURE_PACK",
        "Submit Proposal - DRIVE_ASSURE_PACK",
        "Lead Creation - Proposal",
        "Premium Calculation - od_only",
        "Proposal Generation - od_only",
        "Create Policy Holder",
        "Private Car Proposal Service",
        "Proposal Generation2",
        "TP Premium Calculation",
        "Proposal Generation - DRIVE_ASSURE_PACK_PLUS",
        "create receipt",
        "bike Proposal Service",
        "Premium First Call - GDD",
        "Premium Recalculation - GDD",
        "Proposal Generation - GDD",
        "Renewal Proposal Service",
        "Update Policy Details",
        "Renewal Proposal Submit",
        "Premium Calculation Initial IDV",
        "Premium Calculation With IDV",
        "Renewal Premium Calculate",
        "Premium Calculation - IMT-23",
        "Proposal Submit - IMT-23",
        "Get Proposal",
        "Proposal Generation - Prime",
        "Update CKYC Details",
    ],
    'proposalAllMethods' => [
        "tokenGeneration" => "Token Generation",
        "premiumCalculation" => "Premium Calculation",
        "proposalService" => "Proposal Submit",
        // "Check Breakin Status" => ,
        "Premium Calculation" => "Premium Calculation",
        "Proposal Submit" => "Proposal Submit",
        "Proposal Generation" => "Proposal Submit",
        // "PROPOSAL KYC STATUS",
        // "Validate Proposal",
        // "Pin Generation",
        "Coverage Calculation" => "Premium Calculation",
        "Proposal Creation" => "Proposal Submit",
        // "Lead Creation",
        // "Breakin-Generation",
        "Premium Calculation - Full Quote" => "Proposal Submit",
        "Proposal Submition" => "Proposal Submit",
        "Proposal Creation - Reliance Finsall" => "Proposal Submit",
        "Quote" => "Premium Calculation",
        // "Customer Creation",
        "Get Token" => "Token Generation",
        "Token Generation" => "Token Generation",
        "Premium Calculation - Quote" => "Premium Calculation",
        "Quote Generation" => "Premium Calculation",
        "Premium Recalculation" => "Premium Calculation",
        "Quote Calculation - Quote" => "Premium Calculation",
        "Token genration" => "Token Generation",
        // "Trace Id Generation",
        "Proposal Service" => "Proposal Submit",
        "Update Premium Calculation" => "Premium Calculation",
        "Premium Re-calculation" => "Premium Calculation",
        "Premium submition" => "Proposal Submit",
        "Proposal Submission" => "Proposal Submit",
        "Proposal Submition - Proposal" => "Proposal Submit",
        "Quick Quote - Proposal" => "Premium Calculation",
        "Full Quote - Proposal" => "Premium Calculation",
        // "IIB Verification",
        // "Proposal Status",
        // "Save Quote And Approve Proposal",
        // "Breakin Creation",
        // "Break-in Id Generation",
        // "Break id generation",
        // "Proposal Approval",
        // "Proposal",
        "Submit Proposal" => "Proposal Submit",
        // "save motor quotation",
        // "generate transation",
        // "save motor proposal",
        // "Lead Creation - Proposal",
        // "Create Policy Holder",
        "Private Car Proposal Service" => "Proposal Submit",
        // "Proposal Generation2",
        // "TP Premium Calculation",
        // "create receipt",
        "bike Proposal Service" => "Proposal Submit",
        // "Premium Calculation post Inspection",
        // "Proposal Generation post Inspection",
        "Premium First Call - GDD" => "Premium Calculation",
        "Premium Recalculation - GDD" => "Premium Calculation",
        "Proposal Generation - GDD" => "Proposal Submit",
        "Renewal Proposal Service" => "Proposal Submit",
        // "Update Policy Details",
        "Renewal Proposal Submit" => "Proposal Submit",
        "Premium Calculation Initial IDV" => "Premium Calculation",
        "Premium Calculation With IDV" => "Premium Calculation",
        "Renewal Premium Calculate" => "Premium Calculation",
        "Premium Calculation - IMT-23" => "Premium Calculation",
        "Proposal Submit - IMT-23" => "Proposal Submit",
        // "Get Proposal",
        // "Proposal Generation - Prime",
        // "Update CKYC Details",
    ],
    'policy' => [
        "RE HIT PDF",
        "policyPdfGeneration",
        "Check Policy Status",
        "Policy PDF",
        "policyGeneration",
        "Generate Policy Motor",
        "Generate Policy - Policy No",
        "current PDF Service - PDF",
        "PDF Service - PDF",
        "PDF Generation",
        "Policy Issurance",
        "PDF Service",
        "Policy Generation",
        "Pdf Genration",
        "Document Generation",
        "Policy Download - Payment",
        "Policy Document Download",
        "Fetch policy Document",
        "Policy Number Generation",
        "Generate pdf",
        "Generate Policy",
        "Policy Download - Payment pdf",
        "Policy Number Generation - Payment",
        "Policy PDF Generation - Payment",
        "Fetch Policy Details",
    ],
];
